import assert from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import test from 'node:test'
import { fixture } from './support.js'
const exec = promisify(execFile)
const node = (id, prerequisites = [], challengeVersion = '1.0.0') => ({ id, prerequisites, challengeId: 'mathematics', challengeVersion })
const definition = { schemaVersion: 1, id: 'intro', version: '1.0.0', title: 'Intro', nodes: [node('a'), node('b'), node('c', ['a', 'b'])] }
const key = () => ({ idempotencyKey: randomUUID() })
const terminal = (type = 'attempt_completed') => ({ eventId: randomUUID(), sequence: 2, type, payload: {} })
async function setup(t) {
  const mod = await import('../../dist/modules/campaigns/store.js').catch(error => { if (error.code !== 'ERR_MODULE_NOT_FOUND') throw error; return {} })
  assert.equal(typeof mod.CampaignStore, 'function', 'campaign store implemented')
  const f = await fixture(t), campaigns = new mod.CampaignStore(f.database)
  const user = await f.identities.resolve({ provider: 'clerk', issuer: 'https://campaign.test', subject: 'alice', sessionId: 's' })
  const bob = await f.identities.resolve({ provider: 'clerk', issuer: 'https://campaign.test', subject: 'bob', sessionId: 's' })
  await campaigns.publish(definition)
  return { ...f, campaigns, user, bob, start: (id, input = key(), version = '1.0.0') => campaigns.start(user.id, 'intro', version, id, input) }
}
const status = expected => error => error.status === expected

test('published versions and attempt bindings are immutable and reference exact node challenge', async t => {
  const f = await setup(t)
  await f.campaigns.publish(definition)
  await assert.rejects(f.campaigns.publish({ ...definition, title: 'Changed' }), status(409))
  await assert.rejects(f.campaigns.publish({ ...definition, nodes: [node('a', ['missing'])] }), status(400))
  const a = await f.start('a')
  for (const table of ['campaign_versions', 'campaign_attempts']) for (const query of [`UPDATE ${table} SET ${table === 'campaign_versions' ? 'title=title' : 'node_id=node_id'}`, `DELETE FROM ${table}`, `TRUNCATE ${table} CASCADE`]) await assert.rejects(f.database.pool.query(query), error => error.code === '55000')
  assert.equal((await f.campaigns.get('intro', '1.0.0')).title, 'Intro')
  assert.equal((await f.store.get(f.user.id, a.attempt.id)).progress.status, 'active')
  const unrelated = await f.store.create(f.user.id, { ...key(), challengeId: 'science', challengeVersion: '1.0.0' })
  await assert.rejects(f.database.pool.query('INSERT INTO campaign_attempts(attempt_id,campaign_id,campaign_version,node_id) VALUES($1,$2,$3,$4)', [unrelated.attempt.id, 'intro', '1.0.0', 'a']))
  await assert.rejects(f.database.pool.query('INSERT INTO campaign_attempts(attempt_id,campaign_id,campaign_version,node_id) VALUES($1,$2,$3,$4)', [unrelated.attempt.id, 'intro', '1.0.0', 'missing']))
})
test('events drive AND unlocks, retries and monotonic completion independent of cached progress', async t => {
  const f = await setup(t)
  await assert.rejects(f.start('c'), status(409))
  const a = await f.start('a')
  await assert.rejects(f.start('a'), status(409))
  await f.store.append(f.user.id, a.attempt.id, terminal('attempt_abandoned'))
  assert.equal((await f.campaigns.progress(f.user.id, 'intro', '1.0.0')).nodes[0].canStart, true)
  await assert.rejects(f.start('c'), status(409))
  const retry = await f.start('a'); await f.store.append(f.user.id, retry.attempt.id, terminal())
  await assert.rejects(f.start('c'), status(409))
  const b = await f.start('b'); await f.store.append(f.user.id, b.attempt.id, terminal())
  const c = await f.start('c'); await f.store.append(f.user.id, c.attempt.id, terminal())
  const replay = await f.start('a')
  let progress = await f.campaigns.progress(f.user.id, 'intro', '1.0.0')
  assert.equal(progress.status, 'completed'); assert.equal(progress.nodes[0].attempts, 3)
  assert.equal(progress.nodes[0].canStart, false)
  await f.store.append(f.user.id, replay.attempt.id, terminal('attempt_abandoned'))
  progress = await f.campaigns.progress(f.user.id, 'intro', '1.0.0')
  assert.equal(progress.status, 'completed'); assert.equal(progress.nodes[0].canStart, true)
  await f.database.pool.query('DELETE FROM attempt_progress')
  assert.deepEqual(await f.campaigns.progress(f.user.id, 'intro', '1.0.0'), progress)
  await f.store.rebuild()
  assert.deepEqual(await f.campaigns.progress(f.user.id, 'intro', '1.0.0'), progress)
})
test('concurrent starts serialize active attempts and exact retries including after terminal', async t => {
  const f = await setup(t), input = key()
  const results = await Promise.all(Array.from({ length: 6 }, () => f.start('a', input)))
  assert.equal(results.filter(r => !r.duplicate).length, 1)
  assert.equal(new Set(results.map(r => r.attempt.id)).size, 1)
  const race = await Promise.allSettled(Array.from({ length: 6 }, () => f.start('b')))
  assert.equal(race.filter(r => r.status === 'fulfilled').length, 1)
  for (const r of race.filter(r => r.status === 'rejected')) assert.equal(r.reason.status, 409)
  await f.store.append(f.user.id, results[0].attempt.id, terminal())
  assert.equal((await f.start('a', input)).attempt.id, results[0].attempt.id)
  const counts = await f.database.pool.query('SELECT (SELECT count(*) FROM attempts)::int AS attempts,(SELECT count(*) FROM learning_events)::int AS events,(SELECT count(*) FROM campaign_attempts)::int AS bindings')
  assert.deepEqual(counts.rows[0], { attempts: 2, events: 3, bindings: 2 })
})
test('standalone, owner, node and version contexts cannot share idempotency or learning credit', async t => {
  const f = await setup(t), input = key()
  const standalone = await f.store.create(f.user.id, { ...input, challengeId: 'mathematics', challengeVersion: '1.0.0' })
  await f.store.append(f.user.id, standalone.attempt.id, terminal())
  await assert.rejects(f.start('a', input), status(409))
  const campaignKey = key(), a = await f.start('a', campaignKey)
  await f.store.append(f.user.id, a.attempt.id, terminal())
  await assert.rejects(f.store.create(f.user.id, { ...campaignKey, challengeId: 'mathematics', challengeVersion: '1.0.0' }), status(409))
  await assert.rejects(f.start('b', campaignKey), status(409))
  await f.campaigns.publish({ ...definition, version: '2.0.0', nodes: [node('a', [], '2.0.0'), node('b', ['a'])] })
  await assert.rejects(f.start('a', campaignKey, '2.0.0'), status(409))
  assert.equal((await f.campaigns.progress(f.user.id, 'intro', '1.0.0')).completedNodes, 1)
  assert.equal((await f.campaigns.progress(f.bob.id, 'intro', '1.0.0')).completedNodes, 0)
  assert.equal((await f.campaigns.progress(f.user.id, 'intro', '2.0.0')).status, 'not_started')
  const newAttempt = await f.start('a', key(), '2.0.0')
  assert.equal(newAttempt.attempt.challengeVersion, '2.0.0')
  assert.equal((await f.campaigns.get('intro', '1.0.0')).nodes[0].challengeVersion, '1.0.0')
  await assert.rejects(f.campaigns.progress(f.user.id, 'intro', '3.0.0'), status(404))
  await assert.rejects(f.start('missing'), status(404))
})
test('catalog pages do not drop versions and opt-in seed CLI is repeatable without user events', async t => {
  const f = await setup(t)
  for (let i = 0; i < 51; i++) await f.campaigns.publish({ ...definition, version: `1.0.${i + 1}` })
  const first = await f.campaigns.list({}), second = await f.campaigns.list(first.nextCursor)
  assert.equal(first.items.length, 50); assert.equal(second.items.length, 2); assert.equal(second.nextCursor, null)
  assert.equal(new Set([...first.items, ...second.items].map(x => x.id + '@' + x.version)).size, 52)
  const cli = () => exec(process.execPath, [new URL('../../dist/database/cli.js', import.meta.url).pathname, 'seed-campaigns'], { env: { ...process.env, DATABASE_URL: f.url } })
  await cli(); await cli()
  const seed = await f.campaigns.get('official-intro', '1.0.0')
  assert.deepEqual(seed.nodes.map(n => [n.challengeId, n.challengeVersion]), [['mathematics', '1.0.0'], ['science', '1.0.0']])
  assert.equal((await f.database.pool.query('SELECT count(*)::int AS n FROM learning_events')).rows[0].n, 0)
})
