import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
test.use({ viewport: { width: 1280, height: 800 }, launchOptions: { args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] } })
test.describe('shared Three.js world', () => {
  test.setTimeout(120000)
  test('SSR does not execute the world; browser loads it with original help and controls', async ({ page, request }) => {
    const html = await (await request.get('/play')).text()
    expect(html).not.toContain('<canvas')
    expect(html).not.toContain('WebGLRenderer')
    const requests: string[] = []; const errors: string[] = []
    page.on('request', request => requests.push(request.url()))
    page.on('pageerror', error => errors.push(error.message))
    await page.addInitScript(() => localStorage.setItem('mimix-onboarding-v2', 'seen'))
    await page.goto('/play')
    await expect(page.locator('#canvas')).toBeVisible()
    await expect(page.locator('#world-loading')).toHaveCount(0, { timeout: 90000 })
    await expect(page.getByRole('button', { name: 'Abrir guía de uso' })).toBeVisible()
    await page.getByRole('button', { name: 'Abrir guía de uso' }).click()
    await expect(page.getByRole('heading', { name: 'Mueve a Wall-E' })).toBeVisible()
    await page.getByRole('button', { name: 'Siguiente' }).click()
    await expect(page.getByRole('heading', { name: 'Explora la cámara' })).toBeVisible()
    await page.getByRole('button', { name: 'Comenzar' }).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
    await page.keyboard.down('ArrowUp'); await page.waitForTimeout(500); await page.keyboard.up('ArrowUp')
    await page.mouse.move(640, 400); await page.mouse.wheel(0, -200)
    await page.screenshot({ path: 'test-results/play.png' })
    expect(requests.filter(url => url.endsWith('.glb')).length).toBeGreaterThanOrEqual(5)
    expect(requests.some(url => /\/api\/(robot|voice|challenges\/events)/.test(url))).toBe(false)
    expect(errors).toEqual([])
  })
  test('asset failure exposes retry, which can recover without changing the world', async ({ page }) => {
    await page.route('**/assets/models/islands/home.glb', route => route.fulfill({ status: 503 }))
    await page.goto('/play')
    await expect(page.getByText('No pudimos cargar el mundo.', { exact: true })).toBeVisible()
    await expect(page.locator('#play-state-announcement')).toContainText('No pudimos cargar la experiencia')
    await expect(page.getByRole('button', { name: 'Volver a intentar' })).toBeVisible()
    await page.unroute('**/assets/models/islands/home.glb')
    await page.getByRole('button', { name: 'Volver a intentar' }).click()
    await expect(page.locator('#canvas')).toBeVisible()
    await expect(page.locator('#world-loading')).toHaveCount(0, { timeout: 90000 })
  })
  test('exposes useful status, capability limits and a keyboard-accessible canvas alternative', async ({ page }) => {
    await page.addInitScript(() => localStorage.setItem('mimix-onboarding-v2', 'seen'))
    await page.goto('/play')
    await expect(page.locator('#canvas')).toBeVisible()
    await expect(page.locator('#world-loading')).toHaveCount(0, { timeout: 90000 })

    await expect(page.locator('#play-state-announcement')).toContainText('Mundo listo')
    await expect(page.getByLabel('Mundo 3D de Mimix')).toHaveAccessibleDescription(/Wall-E está en un mapa flotante con dos portales/)
    const cdp = await page.context().newCDPSession(page)
    const domDocument = await cdp.send('DOM.getDocument')
    const host = await cdp.send('DOM.querySelector', { nodeId: domDocument.root.nodeId, selector: '[aria-label="Mundo 3D de Mimix"]' })
    const tree = await cdp.send('Accessibility.getPartialAXTree', { nodeId: host.nodeId, fetchRelatives: false })
    expect(tree.nodes[0]?.description?.value).toContain('Wall-E está en un mapa flotante con dos portales')
    const summary = page.locator('.play-experience summary')
    await summary.focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('heading', { name: 'Explora el mundo a tu manera' })).toBeVisible()
    await expect(page.getByText('Servicios en vivo')).toBeVisible()
    await expect(page.getByText('No conectados')).toBeVisible()
    await expect(page.getByText('Agente, progreso y robot no están disponibles en este entorno.')).toBeVisible()
    await expect(page.getByRole('link', { name: 'Ir directamente a Matemáticas' })).toHaveAttribute('href', 'http://localhost:5173/challenges/mathematics/')
    await expect(page.getByRole('link', { name: 'Ir directamente a Ciencias' })).toHaveAttribute('href', 'http://localhost:5173/challenges/science/')
    expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  })
  test('announces offline degradation without hiding the loaded world', async ({ page, context }) => {
    await page.addInitScript(() => localStorage.setItem('mimix-onboarding-v2', 'seen'))
    await page.goto('/play')
    await expect(page.locator('#world-loading')).toHaveCount(0, { timeout: 90000 })
    await expect(page.locator('#play-state-announcement')).toContainText('Mundo listo')

    await context.setOffline(true)
    await page.evaluate(() => window.dispatchEvent(new Event('offline')))
    await expect(page.locator('#play-state-announcement')).toContainText('Sin conexión')
    await expect(page.locator('#canvas')).toBeVisible()
    await page.locator('.play-experience summary').click()
    await expect(page.locator('.play-notice')).toContainText('El mundo cargado sigue disponible')
  })
  test('does not claim the world is loaded when connection drops during loading', async ({ page, context }) => {
    await page.route('**/assets/models/islands/home.glb', async route => {
      await new Promise(resolve => setTimeout(resolve, 5_000))
      await route.continue()
    })
    await page.goto('/play')
    await expect(page.locator('#world-loading')).toBeVisible()

    await context.setOffline(true)
    await page.evaluate(() => window.dispatchEvent(new Event('offline')))
    await expect(page.locator('#play-state-announcement')).toContainText('Sin conexión durante la carga')
    await expect(page.locator('#play-state-announcement')).not.toContainText('mundo cargado')
    await page.locator('.play-experience summary').click()
    await expect(page.locator('.play-notice')).toContainText('Recupera la conexión para terminar de preparar el mundo')
  })
  test('BFCache exit releases the old canvas and restoration loads a fresh world', async ({ page }) => {
    await page.addInitScript(() => localStorage.setItem('mimix-onboarding-v2', 'seen'))
    await page.goto('/play')
    await expect(page.locator('#canvas')).toBeVisible()
    await expect(page.locator('#world-loading')).toHaveCount(0, { timeout: 90000 })
    await page.evaluate(() => window.dispatchEvent(new PageTransitionEvent('pagehide', { persisted: true })))
    await expect(page.locator('#canvas')).toHaveCount(0)
    await page.evaluate(() => window.dispatchEvent(new PageTransitionEvent('pageshow', { persisted: true })))
    await expect(page.locator('#canvas')).toBeVisible()
    await expect(page.locator('#world-loading')).toHaveCount(0, { timeout: 90000 })
  })

})
