import { test, expect } from '@playwright/test'
test.use({ viewport: { width: 1280, height: 800 }, launchOptions: { args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] } })
test.describe('shared Three.js world', () => {
  test.setTimeout(120000)
  test('SSR does not execute the world; browser loads it with original help and controls', async ({ page, request }) => {
    const html = await (await request.get('/play')).text()
    expect(html).not.toContain('<canvas')
    expect(html).not.toContain('WebGLRenderer')
    const requests: string[] = []; const errors: string[] = []
    page.on('request', request => requests.push(request.url()))
    page.on('pageerror', error => errors.push(error.message))
    await page.addInitScript(() => localStorage.setItem('mimix-onboarding-v2', 'seen'))
    await page.goto('/play')
    await expect(page.locator('#canvas')).toBeVisible()
    await expect(page.locator('#world-loading')).toHaveCount(0, { timeout: 90000 })
    await expect(page.getByRole('button', { name: 'Abrir guía de uso' })).toBeVisible()
    await page.getByRole('button', { name: 'Abrir guía de uso' }).click()
    await expect(page.getByRole('heading', { name: 'Mueve a Wall-E' })).toBeVisible()
    await page.getByRole('button', { name: 'Siguiente' }).click()
    await expect(page.getByRole('heading', { name: 'Explora la cámara' })).toBeVisible()
    await page.getByRole('button', { name: 'Comenzar' }).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
    await page.keyboard.down('ArrowUp'); await page.waitForTimeout(500); await page.keyboard.up('ArrowUp')
    await page.mouse.move(640, 400); await page.mouse.wheel(0, -200)
    await page.screenshot({ path: 'test-results/play.png' })
    expect(requests.filter(url => url.endsWith('.glb')).length).toBeGreaterThanOrEqual(5)
    expect(requests.some(url => /\/api\/(robot|voice|challenges\/events)/.test(url))).toBe(false)
    expect(errors).toEqual([])
  })
  test('asset failure exposes retry, which can recover without changing the world', async ({ page }) => {
    await page.route('**/assets/models/islands/home.glb', route => route.fulfill({ status: 503 }))
    await page.goto('/play')
    await expect(page.getByText('No pudimos cargar el mundo.', { exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Volver a intentar' })).toBeVisible()
    await page.unroute('**/assets/models/islands/home.glb')
    await page.getByRole('button', { name: 'Volver a intentar' }).click()
    await expect(page.locator('#canvas')).toBeVisible()
    await expect(page.locator('#world-loading')).toHaveCount(0, { timeout: 90000 })
  })
  test('BFCache exit releases the old canvas and restoration loads a fresh world', async ({ page }) => {
    await page.addInitScript(() => localStorage.setItem('mimix-onboarding-v2', 'seen'))
    await page.goto('/play')
    await expect(page.locator('#canvas')).toBeVisible()
    await expect(page.locator('#world-loading')).toHaveCount(0, { timeout: 90000 })
    await page.evaluate(() => window.dispatchEvent(new PageTransitionEvent('pagehide', { persisted: true })))
    await expect(page.locator('#canvas')).toHaveCount(0)
    await page.evaluate(() => window.dispatchEvent(new PageTransitionEvent('pageshow', { persisted: true })))
    await expect(page.locator('#canvas')).toBeVisible()
    await expect(page.locator('#world-loading')).toHaveCount(0, { timeout: 90000 })
  })

})
